apiVersion: v2
name: smartops-anomaly
description: SmartOps Anomaly Detection Service - AI-powered anomaly detection
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - smartops
  - anomaly
  - ai
  - machine-learning
  - detection
home: https://github.com/sachinfer/SmartOps
sources:
  - https://github.com/sachinfer/SmartOps
maintainers:
  - name: SmartOps Team
    email: team@smartops.com