# Default values for smartops-anomaly
image:
  repository: us-docker.pkg.dev/icbt-465109/smartops-repo/smartops-anomaly
  tag: "0f72817"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

replicaCount: 1

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Pod annotations
podAnnotations: {}

# Image pull secrets
imagePullSecrets: []

# Service account configuration
serviceAccount:
  create: true
  name: ""

# Pod security context
podSecurityContext: {}

# Container security context
securityContext: {}

# Environment variables
env: []

# Node selector
nodeSelector: {}

# Affinity
affinity: {}

# Tolerations
tolerations: []
