# Default values for smartops-anomaly
image:
  repository: us-docker.pkg.dev/icbt-465109/smartops-repo/smartops-anomaly
  tag: "db79aa2"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"

model:
  enabled: true
  mountPath: /app/model
  pvcName: smartops-anomaly-model

replicaCount: 1
