apiVersion: v2
name: smartops-monitor
description: A Helm chart for SmartOps Monitor
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - smartops
  - monitor
  - monitoring
home: https://github.com/sachinfer/smartops
sources:
  - https://github.com/sachinfer/smartops
maintainers:
  - name: sachinfer
    email: sachinnavoda74@gmail.com
