# Default values for smartops-monitor
image:
  repository: us-docker.pkg.dev/sachinfer/smartops-repo/smartops-monitor
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
