# Default values for smartops-monitor
image:
  repository: us-docker.pkg.dev/sachinfer/smartops-repo/smartops-monitor
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    memory: "16Mi"
    cpu: "10m"
  limits:
    memory: "32Mi"
    cpu: "25m"

replicaCount: 1

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Model configuration
model:
  enabled: false
  mountPath: "/app/model"
  pvcName: "monitor-model-pvc"

# Pod annotations
podAnnotations: {}

# Image pull secrets
imagePullSecrets:
  - name: gcp-registry-secret

# Service account configuration
serviceAccount:
  create: true
  name: ""

# Pod security context
podSecurityContext: {}

# Container security context
securityContext: {}

# Environment variables
env: []

# Node selector
nodeSelector: {}

# Affinity
affinity: {}

# Tolerations
tolerations: []
