apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartops-anomaly.fullname" . }}
  labels:
    {{- include "smartops-anomaly.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "smartops-anomaly.selectorLabels" . | nindent 4 }}
