apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartops-monitor.fullname" . }}
  labels:
    {{- include "smartops-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "smartops-monitor.selectorLabels" . | nindent 4 }}
